version: "3.8"

services:
    # The Laravel PHP app
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini # PHP config
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=${APP_KEY} # Use Laravel's .env key
        depends_on:
            - mysql
        networks:
            - laravel

    # Nginx web server for Laravel
    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        depends_on:
            - app
        ports:
            - "8000:80" # Expose port 80 for HTTP
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Custom Nginx config
        networks:
            - laravel

    # MySQL database
    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    # PHPMyAdmin (optional)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
